### ISSUE TITLE
Server 코드 돌릴때 나는 문제 

### ISSUE THREAD

**Issue by samslow** [DdukTwiSun/server#5]
README.md 순서대로 진행했습니다.

다만 0.0.0.0 adress가 사용중이라 localhost로 하였고, flask 가 production은 local에서 안 돌아가서 FLASK_ENV=development 옵션을 주었습니다.

```shell
myvenv > sudo FLASK_APP=server/api.py FLASK_ENV=development myvenv/bin/python3 -m flask run  --port=80
```

위와같이 하였을 때 아래와 같은 에러가 나는데 해결방법 아시는 분 있튀순?

```python
Traceback (most recent call last):
  File "/Users/samslow/Desktop/GitProject/server/myvenv/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
ModuleNotFoundError: No module named 'api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/samslow/Desktop/GitProject/server/myvenv/lib/python3.7/site-packages/flask/cli.py", line 330, in __call__
    rv = self._load_unlocked()
  File "/Users/samslow/Desktop/GitProject/server/myvenv/lib/python3.7/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/Users/samslow/Desktop/GitProject/server/myvenv/lib/python3.7/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/Users/samslow/Desktop/GitProject/server/myvenv/lib/python3.7/site-packages/flask/cli.py", line 246, in locate_app
    'Could not import "{name}".'.format(name=module_name)
flask.cli.NoAppException: Could not import "api".
127.0.0.1 - - [20/Mar/2019 08:07:04] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 08:07:04] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 08:07:04] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 08:07:04] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 08:07:04] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 08:07:04] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by zerone2** [comment]
imagemagick 재설치 해보셈

**Comment by zerone2** [comment]
> imagemagick 재설치 해보셈

그 문제가 아니네
패키지 문제같은데...

**Comment by samslow** [comment]
> > imagemagick 재설치 해보셈
> 
> 그 문제가 아니네
> 패키지 문제같은데...

wand version은 5 버전까지 올라가긴 했는데 기존 0.4.4 버전으로 설치했는데 나두 잘 안대넹

**Comment by zerone2** [comment]
재학이형이나 재호한테 물어봐야될듯?
